[buildPlans.cambridge-sans]      # <cambridge-sans> is your plan name
family = "Cambridge Sans"        # Font menu family name
spacing = "quasi-proportional"   # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
serifs = "sans"                  # Optional; Values: `sans` or `slab`
no-cv-ss = "true"

###################################################################################################
# Configure variants

[buildPlans.cambridge-sans.variants.design]
capital-j = "serifless"
capital-k = "symmetric-touching-serifless"
capital-q = "crossing"
capital-w = "straight-flat-top"
capital-m = "flat-bottom"
capital-i = "serifless"
f = "flat-hook"
g = "double-storey"
i = "serifless"
j = "flat-hook-serifless"
k = "symmetric-touching-serifless"
l = "flat-tailed"
t = "flat-hook"
w = "straight-flat-top"
eszet = "sulzbacher-descending"
lower-alpha = "tailed-barred"
cyrl-capital-ka = "symmetric-touching-serifless"
cyrl-ka = "symmetric-touching-serifless"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "closed"
five = "oblique-upper-left-bar"
eight = "two-circles"
brace = "straight"
number-sign = "slanted"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"

[buildPlans.cambridge-sans.variants.italic]

f = "flat-hook-tailed"
g = "single-storey-serifless"
# End variant section
###################################################################################################

###################################################################################################
# Override default building slope sets
# When this section is absent, all slopes would be built.

[buildPlans.cambridge-sans.slopes.upright]
shape = "upright"     # Slope grade used for shape selection.  `upright` | `oblique` | `italic`
menu  = "upright"     # Slope grade used for naming.           `upright` | `oblique` | `italic`
css   = "normal"      # Slope grade used for webfont CSS.      `normal`  | `oblique` | `italic`
angle = 0

[buildPlans.cambridge-sans.slopes.italic]
shape = "italic"
menu  = "italic"
css   = "italic"
angle = 15

# End slope section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports numbers between 434 and 664 (inclusive),
#             while "menu" only supports integers between 1 and 9 (inclusive).
#             The "shape" parameter specifies the unit width, measured in 1/1000 em. The glyphs'
#             width are equal to, or a simple multiple of the unit width.
#             If you decide to use custom widths you have to define all the widths you plan to use,
#             otherwise they will not be built.

[buildPlans.cambridge-sans.widths.normal]
shape = 600        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.

# End width section
###################################################################################################
