
[buildPlans.CambridgeSans]      # <CambridgeSans> is your plan name
family = "Cambridge Sans"        # Font menu family name
spacing = "quasi-proportional"               # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
copyright = "Copyright 2026 The Cambridge Project Authors"
designer = "Cristiano Sobral, Belleve Invis"
serifs = "sans"                  # Optional; Values: `sans` or `slab`
exportGlyphNames = false       # Set this to true for ligature support in Kitty (increased file size)
noCvSs = true
noLigation = true
webfontFormats = ['ttf', 'woff2']


[buildPlans.CambridgeSans.variants.design]
zero = 'oval-unslashed'
one = 'base'
two = 'straight-neck-serifless'
three = 'two-arcs'
four = 'closed-serifless'
five = 'upright-arched-serifless'
six = 'closed-contour'
seven = 'bend-serifless'
eight = 'two-circles'
nine = 'closed-contour'
capital-a = 'straight-serifless'
capital-b = 'standard-serifless'
capital-c = 'serifless'
capital-d = 'more-rounded-serifless'
capital-e = 'serifless'
capital-f = 'serifless'
capital-g = 'toothless-rounded-serifless-hooked'
capital-h = 'serifless'
capital-i = 'short-serifed'
capital-j = 'serifless'
capital-k = 'straight-serifless'
capital-l = 'serifless'
capital-m = 'hanging-serifless'
capital-n = 'standard-serifless'
capital-p = 'closed-serifless'
capital-q = 'curly-tailed'
capital-r = 'straight-serifless'
capital-s = 'serifless'
capital-t = 'serifless'
capital-u = 'toothless-rounded-serifless'
capital-v = 'straight-serifless'
capital-w = 'straight-almost-flat-top-serifless'
capital-x = 'straight-serifless'
capital-y = 'straight-serifless'
capital-z = 'straight-serifless'
a = 'double-storey-serifless'
b = 'toothed-serifless'
c = 'serifless'
d = 'toothed-serifless'
e = 'flat-crossbar'
f = 'flat-hook-serifless-crossbar-at-x-height'
g = 'single-storey-serifless'
h = 'straight-serifless'
i = 'serifless'
j = 'flat-hook-serifless'
k = 'straight-serifless'
l = 'serifless'
m = 'serifless'
n = 'straight-serifless'
p = 'eared-serifless'
q = 'straight-serifless'
r = 'compact-serifless'
s = 'serifless'
t = 'flat-hook'
u = 'toothed-serifless'
v = 'straight-serifless'
w = 'straight-flat-top-serifless'
x = 'straight-serifless'
y = 'straight-turn-serifless'
z = 'straight-serifless'
capital-eszet = 'rounded-serifless'
long-s = 'flat-hook-serifless'
eszet = 'longs-s-lig-serifless'
lower-eth = 'curly-bar'
capital-thorn = 'serifless'
capital-gamma = 'serifless'
capital-delta = 'straight'
capital-lambda = 'straight-serifless'
lower-thorn = 'serifless'
lower-alpha = 'crossing'
lower-beta = 'standard'
lower-delta = 'rounded'
lower-eta = 'serifless'
lower-iota = 'flat-tailed'
lower-kappa = 'straight-serifless'
lower-lambda = 'straight-turn'
lower-tau = 'flat-tailed'
lower-theta = 'oval'
lower-gamma = 'casual'
lower-pi = 'tailed'
lower-mu = 'tailed-serifless'
lower-nu = 'casual'
lower-phi = 'cursive'
lower-upsilon = 'casual-serifless'
lower-xi = 'rounded'
lower-psi = 'serifless'
lower-chi = 'straight-serifless'
cyrl-a = 'double-storey-serifless'
cyrl-ve = 'standard-serifless'
cyrl-capital-zhe = 'straight'
cyrl-zhe = 'straight'
cyrl-capital-ze = 'serifless'
cyrl-ze = 'serifless'
cyrl-capital-ka = 'straight-serifless'
cyrl-ka = 'straight-serifless'
cyrl-em = 'hanging-serifless'
cyrl-capital-en = 'serifless'
cyrl-en = 'serifless'
cyrl-capital-er = 'closed-serifless'
cyrl-er = 'eared-serifless'
cyrl-capital-u = 'straight-turn-serifless'
cyrl-u = 'straight-turn-serifless'
cyrl-ef = 'split-serifless'
cyrl-capital-e = 'serifless'
cyrl-e = 'serifless'
cyrl-capital-ya = 'straight-serifless'
cyrl-ya = 'straight-serifless'
partial-derivative = 'curly-bar'
tittle = 'square'
diacritic-dot = 'square'
punctuation-dot = 'square'
braille-dot = 'square'
asterisk = 'penta-low'
brace = 'straight'
caret = 'high'
guillemet = 'straight'
at = 'fourfold'
percent = 'rings-continuous-slash'
micro-sign = 'toothed-serifless'


[buildPlans.CambridgeSans.slopes.Upright]
angle = 0             # Angle in degrees. Valid range [0, 15]
shape = "upright"     # Slope grade used for shape selection.  `upright` | `oblique` | `italic`
menu  = "upright"     # Slope grade used for naming.           `upright` | `oblique` | `italic`
css   = "normal"      # Slope grade used for webfont CSS.      `normal`  | `oblique` | `italic`

[buildPlans.CambridgeSans.slopes.Italic]
angle = 11.3
shape = "oblique"
menu  = "italic"
css   = "italic"


[buildPlans.CambridgeSans.widths.Normal]
shape = 600        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.


[buildPlans.CambridgeSans.weights.Thin]
shape = 100  
menu  = 100  
css   = 100

[buildPlans.CambridgeSans.weights.ExtraLight]
shape = 220  
menu  = 200  
css   = 200 

[buildPlans.CambridgeSans.weights.Light]
shape = 340  
menu  = 300  
css   = 300 

[buildPlans.CambridgeSans.weights.Regular]
shape = 460  
menu  = 400  
css   = 400  

[buildPlans.CambridgeSans.weights.Medium]
shape = 570
menu  = 500  
css   = 500

[buildPlans.CambridgeSans.weights.SemiBold]
shape = 680
menu  = 700
css   = 700

[buildPlans.CambridgeSans.weights.Bold]
shape = 790
menu  = 700
css   = 700

[buildPlans.CambridgeSans.weights.ExtraBold]
shape = 900
menu  = 800
css   = 800

[collectPlans.CambridgeSans]
from = ["CambridgeSans"]

[buildPlans.CambridgeSans.metricOverride]
leading = 1000
cap = 637
ascender = 637
xHeight = 456
sb = 'default_sb * 0.83'
symbolMid = 273
essRatioLower = 'default_essRatio * 0.85'



[buildPlans.CambridgeMono]      # <CambridgeSans> is your plan name
family = "Cambridge Mono"        # Font menu family name
spacing = "fixed"               # Optional; Values: `normal`, `term`, `fontconfig-mono`, or `fixed`
copyright = "Copyright 2026 The Cambridge Project Authors"
designer = "Cristiano Sobral, Belleve Invis"
serifs = "sans"                  # Optional; Values: `sans` or `slab`
exportGlyphNames = false       # Set this to true for ligature support in Kitty (increased file size)
noCvSs = true
noLigation = true
webfontFormats = ['ttf', 'woff2']


[buildPlans.CambridgeMono.variants.design]
zero = 'slashed'
one = 'base'
two = 'straight-neck-serifed'
three = 'two-arcs'
four = 'closed-serifed'
five = 'upright-arched-serifless'
six = 'closed-contour'
seven = 'bend-serifed'
eight = 'two-circles'
nine = 'closed-contour'
capital-a = 'straight-serifless'
capital-b = 'standard-serifless'
capital-c = 'unilateral-serifed'
capital-d = 'more-rounded-serifless'
capital-e = 'serifless'
capital-f = 'serifless'
capital-g = 'toothless-rounded-serifed-hooked'
capital-h = 'serifless'
capital-i = 'serifed'
capital-j = 'serifless'
capital-k = 'straight-serifless'
capital-l = 'serifless'
capital-m = 'hanging-serifless'
capital-n = 'standard-serifless'
capital-p = 'closed-serifless'
capital-q = 'curly-tailed'
capital-r = 'straight-serifless'
capital-s = 'bilateral-serifed'
capital-t = 'serifed'
capital-u = 'toothless-rounded-serifless'
capital-v = 'straight-serifless'
capital-w = 'straight-serifless'
capital-x = 'straight-serifed'
capital-y = 'straight-serifed'
capital-z = 'straight-serifed'
a = 'double-storey-serifless'
b = 'toothed-serifless'
c = 'unilateral-serifed'
d = 'toothed-top-serifed'
e = 'flat-crossbar'
f = 'flat-hook-serifed-crossbar-at-x-height'
g = 'single-storey-serifless'
h = 'straight-serifless'
i = 'serifed'
j = 'serifed'
k = 'straight-serifless'
l = 'serifed'
m = 'serifless'
n = 'straight-serifless'
p = 'eared-serifless'
q = 'straight-serifless'
r = 'hookless-serifed'
s = 'serifless'
t = 'bent-hook'
u = 'toothed-serifless'
v = 'straight-serifless'
w = 'straight-flat-top-serifless'
x = 'straight-serifed'
y = 'straight-turn-serifless'
z = 'straight-serifed'
capital-eszet = 'rounded-serifless'
long-s = 'flat-hook-serifless'
eszet = 'longs-s-lig-serifless'
lower-eth = 'curly-bar'
capital-thorn = 'serifless'
capital-gamma = 'serifless'
capital-delta = 'straight'
capital-lambda = 'straight-serifless'
lower-thorn = 'serifless'
lower-alpha = 'crossing'
lower-beta = 'standard'
lower-delta = 'rounded'
lower-eta = 'motion-serifed'
lower-iota = 'serifed-flat-tailed'
lower-kappa = 'straight-serifless'
lower-lambda = 'straight-turn'
lower-tau = 'flat-tailed'
lower-theta = 'oval'
lower-gamma = 'casual'
lower-pi = 'tailed'
lower-mu = 'tailed-serifless'
lower-nu = 'casual'
lower-phi = 'cursive'
lower-upsilon = 'casual-serifless'
lower-xi = 'rounded'
lower-psi = 'serifless'
lower-chi = 'straight-serifless'
cyrl-a = 'double-storey-serifless'
cyrl-ve = 'standard-serifless'
cyrl-capital-zhe = 'straight'
cyrl-zhe = 'straight'
cyrl-capital-ze = 'unilateral-serifed'
cyrl-ze = 'serifless'
cyrl-capital-ka = 'straight-serifless'
cyrl-ka = 'straight-serifless'
cyrl-em = 'hanging-serifless'
cyrl-capital-en = 'serifless'
cyrl-en = 'serifless'
cyrl-capital-er = 'closed-serifless'
cyrl-er = 'eared-serifless'
cyrl-capital-u = 'straight-turn-serifless'
cyrl-u = 'straight-turn-serifless'
cyrl-ef = 'split-serifless'
cyrl-capital-e = 'unilateral-serifed'
cyrl-e = 'serifless'
cyrl-capital-ya = 'straight-serifless'
cyrl-ya = 'straight-serifless'
partial-derivative = 'curly-bar'
tittle = 'square'
diacritic-dot = 'square'
punctuation-dot = 'square'
braille-dot = 'square'
asterisk = 'penta-low'
brace = 'straight'
caret = 'high'
guillemet = 'straight'
at = 'fourfold'
percent = 'rings-continuous-slash'
micro-sign = 'toothed-serifless'




[buildPlans.CambridgeMono.slopes.Upright]
angle = 0             # Angle in degrees. Valid range [0, 15]
shape = "upright"     # Slope grade used for shape selection.  `upright` | `oblique` | `italic`
menu  = "upright"     # Slope grade used for naming.           `upright` | `oblique` | `italic`
css   = "normal"      # Slope grade used for webfont CSS.      `normal`  | `oblique` | `italic`

[buildPlans.CambridgeMono.slopes.Italic]
angle = 11.3
shape = "oblique"
menu  = "italic"
css   = "italic"


[buildPlans.CambridgeMono.widths.Normal]
shape = 600        # Unit Width, measured in 1/1000 em.
menu  = 5          # Width grade for the font's names.
css   = "normal"   # "font-stretch' property of webfont CSS.


[buildPlans.CambridgeMono.weights.Thin]
shape = 100  
menu  = 100  
css   = 100

[buildPlans.CambridgeMono.weights.ExtraLight]
shape = 220  
menu  = 200  
css   = 200 

[buildPlans.CambridgeMono.weights.Light]
shape = 340  
menu  = 300  
css   = 300 

[buildPlans.CambridgeMono.weights.Regular]
shape = 460  
menu  = 400  
css   = 400  

[buildPlans.CambridgeMono.weights.Medium]
shape = 570
menu  = 500  
css   = 500

[buildPlans.CambridgeMono.weights.SemiBold]
shape = 680
menu  = 700
css   = 700

[buildPlans.CambridgeMono.weights.Bold]
shape = 790
menu  = 700
css   = 700

[buildPlans.CambridgeMono.weights.ExtraBold]
shape = 900
menu  = 800
css   = 800



[buildPlans.CambridgeMono.metricOverride]
leading = 1000
cap = 637
ascender = 637
xHeight = 456
sb = 'default_sb * 0.83'
symbolMid = 273
essRatioLower = 'default_essRatio * 0.85'

[collectPlans.CambridgeMono]
from = ["CambridgeMono"]

